### ISSUE TITLE
Morning Session 2: Peer-to-peer Code Review

### ISSUE THREAD

**Issue by mnekx** [Ismailco/Awesome-books-with-ES6#2]
- In file start.js, could the code be more professional if commented code is removed? Otherwise, great modular design. It has been difficult finding issues because of a good job 🤜 🤛 

![image](https://user-images.githubusercontent.com/22321030/154425115-931d4ccd-3add-43fb-80fc-ff5c7e36e0e3.png)

**Comment by zmekonnen251** [comment]
- you did an amazing job. I have only one issue the input and start functions have to be arrow functions, not the regular functions because on the requirement it says we have to use ES6 syntax.
